import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const catalog=JSON.parse(fs.readFileSync(path.join(root,'catalog.json'),'utf8'));
const entries=catalog.slice().sort((a,b)=>!a.page&&!b.page?a.name.localeCompare(b.name):!a.page?-1:!b.page?1:Number(a.page)-Number(b.page));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>维叙 · UX 母版</title><style>
:root{--bg:#f6f5fa;--surface:white;--ink:#252238;--muted:#716b83;--border:#dfdceb;--accent:#6c48d9}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 system-ui,"Microsoft YaHei",sans-serif}header,main{max-width:1600px;margin:auto;padding:28px}header{padding-bottom:18px}h1{font-size:30px;margin:14px 0 8px}p{color:var(--muted);margin:8px 0}a{color:var(--accent)}nav,.filters{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.filters{margin-top:20px}button,input{font:inherit;border:1px solid var(--border);background:var(--surface);color:var(--ink);border-radius:8px;padding:8px 12px}button{cursor:pointer}button[aria-pressed=true]{background:var(--accent);border-color:var(--accent);color:white}input{min-width:230px}main{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;padding-top:0}article{border:1px solid var(--border);border-radius:10px;background:var(--surface);overflow:hidden}article[hidden]{display:none}.preview{display:block;line-height:0}.preview img{width:100%;aspect-ratio:8/5;object-fit:contain;display:block}.caption{padding:12px 16px}.caption h2{font-size:15px;margin:0 0 4px}.caption p{font-size:12px;margin:0;display:flex;justify-content:space-between;gap:12px}.caption span{color:var(--muted)}dialog{width:96vw;max-width:1800px;height:94vh;padding:0;border:1px solid var(--border);border-radius:12px;background:var(--surface)}dialog::backdrop{background:rgba(24,20,36,.72)}.bar{display:flex;gap:12px;align-items:center;padding:12px 16px;border-bottom:1px solid var(--border)}.bar strong{flex:1}.imagebox{height:calc(100% - 64px);overflow:auto;display:flex;justify-content:center;align-items:flex-start}.imagebox img{max-width:100%;max-height:100%;object-fit:contain}:focus-visible{outline:3px solid var(--accent);outline-offset:3px}@media(max-width:1100px){main{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){main{grid-template-columns:1fr}.bar{flex-wrap:wrap}.bar strong{flex-basis:100%}}
</style></head><body><header><nav><a href="../../doc/INDEX.md">文档总索引</a><a href="../../doc/indexes/design.md">交互与视觉</a><a href="README.md">母版说明与状态映射</a><a href="fablevia-ux-master.pen">可编辑 .pen 母版</a></nav><h1>维叙 · UX 母版</h1><p>70 个页面状态 · 8 张设计基础与控件图谱。这里展示 PenCLI 从结构化母版导出的页面，点击图片查看大图。</p><div class="filters" aria-label="筛选"><button aria-pressed="true" data-filter="all">全部</button><button aria-pressed="false" data-filter="components">基础与组件</button><button aria-pressed="false" data-filter="main">主要页面 01–20</button><button aria-pressed="false" data-filter="states">补充状态 21–70</button><input id="search" type="search" aria-label="搜索页面编号或名称" placeholder="搜索页面编号、名称或状态…"></div><p id="count" role="status">${entries.length} 张画板</p></header><main>${entries.map(e=>`<article data-group="${!e.page?'components':Number(e.page)<=20?'main':'states'}" data-search="${escape(e.name+' '+(e.state||''))}"><a class="preview" href="${escape(e.preview)}" data-title="${escape(e.name)}"><img src="${escape(e.preview)}" alt="${escape(e.name)}" loading="lazy"></a><div class="caption"><h2>${escape(e.name)}</h2><p><span>${e.width} × ${e.height}${e.state?' · '+escape(e.state):''}</span><a href="${escape(e.preview)}" target="_blank" rel="noopener">原尺寸</a></p></div></article>`).join('')}</main><dialog aria-label="母版画板大图"><div class="bar"><strong id="title"></strong><button id="prev" aria-label="上一张">←</button><button id="next" aria-label="下一张">→</button><a id="original" target="_blank" rel="noopener">打开原图</a><button id="close">关闭 · Esc</button></div><div class="imagebox"><img id="large" alt=""></div></dialog><script>
const cards=[...document.querySelectorAll('article')],dlg=document.querySelector('dialog');let filter='all',selected=0,active=[];
function apply(){const q=document.querySelector('#search').value.trim().toLowerCase();cards.forEach(c=>c.hidden=(filter!=='all'&&c.dataset.group!==filter)||!c.dataset.search.toLowerCase().includes(q));document.querySelector('#count').textContent=cards.filter(c=>!c.hidden).length+' 张画板';}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));apply()}));document.querySelector('#search').addEventListener('input',apply);
function show(){const a=active[selected];document.querySelector('#large').src=a.href;document.querySelector('#large').alt=a.dataset.title;document.querySelector('#title').textContent=a.dataset.title;document.querySelector('#original').href=a.href;}
document.querySelectorAll('.preview').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();active=cards.filter(c=>!c.hidden).map(c=>c.querySelector('.preview'));selected=active.indexOf(a);show();dlg.showModal();}));function step(d){selected=(selected+d+active.length)%active.length;show();}document.querySelector('#prev').onclick=()=>step(-1);document.querySelector('#next').onclick=()=>step(1);document.querySelector('#close').onclick=()=>dlg.close();dlg.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}});
</script></body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);
console.log(`Generated preview gallery: ${entries.length} artboards`);
